apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: static-app
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
        - name: msapp
          image: durai5050/flask_images:1.0
          ports:
            - containerPort: 5000
