pipeline {
    agent any
    environment {
        DEPLOYMENT_NAME = "msapp-deployment"
        NAMESPACE = "dev"
        REGION    = "ap-south-1"
    }
    parameters {
        choice(
            name: 'ACTION',
            choices: ['DEPLOY_V1', 'DEPLOY_V2', 'ROLLBACK'],
            description: 'Choose deployment action'
        )
        string(
            name: 'ROLLBACK_REVISION',
            defaultValue: '1',
            description: 'Revision number for rollback (only used if ACTION=ROLLBACK)'
        )
    }
    stages {
        stage('Cleanup-WS') {
            steps {
                cleanupWs()
             }
        }
        stage('Checkout') {
            steps {
                git 'https://github.com/thangacodes/Docker.git'
            }
        }
        stage('Deploy V1') {
            when {
                expression { params.ACTION == 'DEPLOY_V1' }
            }
            steps {
                sh '''
                kubectl apply -f Docker/micro-service/manifest-files/svc.yaml -n $NAMESPACE
                kubectl apply -f Docker/micro-service/manifest-files/v1.yaml -n $NAMESPACE
                kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                '''
            }
        }
        stage('Deploy V2') {
            when {
                expression { params.ACTION == 'DEPLOY_V2' }
            }
            steps {
                sh '''
                kubectl apply -f Docker/micro-service/manifest-files/v2.yaml -n $NAMESPACE
                kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                '''
            }
        }
        stage('Check Rollout History') {
            when {
                expression { params.ACTION == 'ROLLBACK' }
            }
            steps {
                sh '''
                kubectl rollout history deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                '''
            }
        }
        stage('Rollback Deployment') {
            when {
                expression { params.ACTION == 'ROLLBACK' }
            }
            steps {
                sh """
                kubectl rollout undo deployment/$DEPLOYMENT_NAME \
                --to-revision=${params.ROLLBACK_REVISION} \
                -n $NAMESPACE
                """
            }
        }
        stage('Verify Rollout') {
            steps {
                sh '''
                kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                '''
            }
        }
    }
}
